SELECT * FROM scientist;
SELECT * FROM scientist_card;
SELECT * FROM species;
SELECT * FROM scientist_observation_ratio;
SELECT * FROM observation;
SELECT * FROM creature;
SELECT * FROM planet;
SELECT * FROM galaxy;
SELECT * FROM journal_article;